FROM node:14

WORKDIR /usr/home/app

COPY package.json ./
COPY tsconfig.json ./
COPY ormconfig.json ./

COPY src ./src
RUN npm install

EXPOSE 4000

COPY wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh