version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    depends_on:
      - database
    command: ["./wait-for-it.sh", "database:3306", "--", "npm", "run", "dev"]
    networks:
      - general
  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: carlos
      MYSQL_PASSWORD: carlos
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - general

networks:
  general:
    driver: bridge
